future: false
lsi: false
pygments: true
permalink: pretty
paginate: 5
auto: true
url: http://www.bounga.org
name: Bounga's Home
exclude: ['README.md', 'Rakefile', 'vendor', 'Gemfile', 'Gemfile.lock']
destination: public
markdown: maruku