permalink: pretty
paginate: 5
url: http://www.bounga.org
name: Bounga's Home
exclude: ['README.md', 'Rakefile', 'vendor', 'Gemfile', 'Gemfile.lock']
destination: public
timezone: Europe/Paris
gems: [jekyll-paginate]
